Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek.Models;
using Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek.Services.Contracts;
using HomeWork_65.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;
        private UserManager<User> _userManager;

        public BasketController(IBasketService basketService, UserManager<User> userManager)
        {
            if (basketService == null)
                throw new ArgumentNullException(nameof(basketService));
            if (userManager == null)
                throw new ArgumentNullException(nameof(userManager));
            _basketService = basketService;
            _userManager = userManager;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {           
            try
            {
                User currentUser = await _userManager.GetUserAsync(User);
                List<BasketModel> model = _basketService.ShowBaskets(currentUser.Id);
                return View(model);
            }
            catch(ArgumentNullException )
            {
                return BadRequest();
            }
            catch (Exception e)
            {
                return StatusCode(500, e);
            }
            
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddToBasket(int id)
        {           
            try
            {
                User currentUser = await _userManager.GetUserAsync(User);
                _basketService.AddToBasket(id, currentUser.Id);
                return RedirectToAction("Index", "Restaurant");
            }
            catch (Exception e)
            {
                return StatusCode(500, e);
            }
        }
    }
}

Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek/Controllers/DishController.cs
using System;
using Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek.Models;
using Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek.Services.Contracts;
using HomeWork_65.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek.Controllers
{
    public class DishController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IDishService _dishService;

        public DishController(UserManager<User> userManager, IDishService dishService)
        {
            if(dishService == null)
                throw new ArgumentNullException(nameof(_dishService));
            if(userManager == null)
                throw new ArgumentNullException(nameof(_userManager));
            _userManager = userManager;
            _dishService = dishService;
        }

        public IActionResult Index()
        {
            try
            {
                var AllDishes = _dishService.GetAllDishes();
                return View(AllDishes);
            }
            catch (ArgumentNullException e)
            {
                throw new ArgumentNullException(nameof(e.Message));
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {            
            try
            {
                var model = _dishService.GetDishCreateModel();
                return View(model);
            }
            catch (ArgumentNullException e)
            {
                throw new ArgumentNullException(nameof(e.Message));
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult CreateDish(DishCreateModel model)
        {
            try
            {
                _dishService.Create(model);
                return RedirectToAction("Index");
            }
            catch (ArgumentNullException e)
            {
                throw new ArgumentNullException(nameof(e.Message));
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }
    }
}

Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek/Views/Shared/_Layout.cshtml
@using HomeWork_65.Entities
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="Index">Dishes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Baskets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Csharp_6_Group_65_HomeWork_Ubaydullaev_Gairatbek - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>